#ifndef def_MS_PER_TIMESTEP
#define def_MS_PER_TIMESTEP

extern int g_MS_PER_TIMESTEP;       //Be sure to declare this in your executable!

#endif

#ifndef TIMEOUTS_H
#define TIMEOUTS_H

//Time of each step in ms
//#define MS_PER_STEP 100
#define MS_PER_STEP g_MS_PER_TIMESTEP
#define SEC_PER_STEP MS_PER_STEP/1000

//VASTClient timeouts
#define _TIMEOUT_JOIN_ 500*SEC_PER_STEP
#define _TIMEOUT_SUBSCRIBE_ 500*SEC_PER_STEP
#define _TIMEOUT_REMOVE_GHOST_ 500*SEC_PER_STEP

//VASTMatcher timeouts
#define _TIMEOUT_SUBSCRIPTION_KEEPALIVE_ 100*SEC_PER_STEP
#define _TIMEOUT_MATCHER_KEEPALIVE_ 1000*SEC_PER_STEP

//VASTRelay timeouts
#define _TIMEOUT_COORD_QUERY_ 3000*SEC_PER_STEP
#define _KEEPALIVE_RELAY_ 500*SEC_PER_STEP
#define _TIMEOUT_RELAY_QUERY_ 500*SEC_PER_STEP
#define _TIMEOUT_RELAY_JOIN_ 500*SEC_PER_STEP

//VASTVerse timeouts
#define _VASTVERSE_RETRY_PERIOD_ 1000*SEC_PER_STEP

//VONPeer timeouts
#define _MAX_DROP_SECONDS_ 200*SEC_PER_STEP
#define _MAX_TIMELY_PERIOD_ 1000*SEC_PER_STEP

//VSOPeer timeouts
#define _VSO_TIMEOUT_OVERLOAD_REQUEST_ 300*SEC_PER_STEP
#define _VSO_TIMEOUT_TRANSFER_ 30*SEC_PER_STEP
#define _VSO_TIMEOUT_AUTO_REMOVE_ 200*SEC_PER_STEP

//VASTnet timeouts
#define _TIMEOUT_CONNECTION_CLEANUP_ 100*SEC_PER_STEP
#define _TIMEOUT_REMOVE_CONNECTION_ 1500*SEC_PER_STEP
#define _TIMEOUT_ID_REQUEST_ 500*SEC_PER_STEP

//net_udp timeouts
#define _UDP_TIMEOUT_MS_ 500*MS_PER_STEP


#define VASTREAL_STEP_DISPLAY_DIVISOR 5000

#endif // TIMEOUTS_H
